version: "3.8"
services:
  admin_service:
    build: 
      context: ./admin_service
    container_name: admin_service_container
    ports:
      - "8000:8000"
    env_file:
      - .env.admin
    depends_on: []
   

  frontend_service:
    build:
      context: ./frontend_service
    container_name: frontend_service_container
    ports:
      - "8001:8001"
    env_file:
      - .env.frontend
    depends_on: []
